"""Local repository generation (git fast-import) and throttled push.

Commits are created locally, with no network. The only calls to GitHub are
`git ls-remote`, one fetch when the remote already holds a drawing, and the
pushes, sent in batches with a pause between them; the pause grows after a
transient failure.

GitHub counts a commit on its author date, whatever its place in the
history: new periods are appended on top of an existing drawing, only a
period drawn again needs the history to be rebuilt.
"""

from __future__ import annotations

import calendar
import re
import shutil
import subprocess
import time
from collections import Counter
from collections.abc import Callable
from datetime import date, datetime, timezone
from pathlib import Path

MARKER_KEY = "cheatmap.generated"
EXISTING_REF = "refs/cheatmap/existing"  # the remote branch, fetched locally
LOG_FILE = "activity.log"
MAX_ATTEMPTS = 4
MAX_DELAY = 60.0
_FATAL = re.compile(
    r"permission denied|repository not found|authentication failed|rejected|non-fast-forward|does not appear",
    re.IGNORECASE,
)


class GitError(RuntimeError):
    pass


_HINTS = (
    (
        r"repository not found|does not appear to be a git repository",
        "repository not found or not accessible: create it on GitHub first "
        "(empty, no README, private is fine: https://github.com/new or `gh repo create <name> --private`) "
        "and check the URL",
    ),
    (
        r"permission denied \(publickey\)|host key verification failed",
        "GitHub refused the SSH connection: check your key with `ssh -T git@github.com`",
    ),
    (
        r"authentication failed|could not read username|terminal prompts disabled",
        "HTTPS authentication failed: use the SSH URL (git@github.com:<user>/<repo>.git) or run `gh auth login`",
    ),
    (
        r"could not resolve host|connection (timed out|refused|reset)|network is unreachable|operation timed out",
        "cannot reach GitHub: check your network",
    ),
    (r"rejected|non-fast-forward", "the remote changed during the run: run it again"),
)


def explain(message: str) -> str | None:
    """Plain-language hint for a git error message, if it is a known case."""
    for pattern, hint in _HINTS:
        if re.search(pattern, message, re.IGNORECASE):
            return hint
    return None


def git(*args: str, cwd: Path | None = None) -> str:
    result = subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True)
    if result.returncode:
        raise GitError(result.stderr.strip() or f"git {args[0]} failed")
    return result.stdout


def remote_branches(remote: str) -> list[str]:
    """Branches on the remote (empty list for a new, empty repository)."""
    output = git("ls-remote", "--heads", remote)
    return [line.split("refs/heads/", 1)[1] for line in output.splitlines() if "refs/heads/" in line]


def prepare_workdir(path: Path) -> None:
    """Remove a previous output of this tool; refuse to touch anything else."""
    if not path.exists():
        return
    if path.is_dir() and not any(path.iterdir()):
        path.rmdir()
        return
    try:
        generated = git("config", "--get", MARKER_KEY, cwd=path).strip() == "true"
    except GitError:
        generated = False
    if not generated:
        raise GitError(f"{path} exists and was not generated by activity-cheatmap, remove it or use --workdir")
    shutil.rmtree(path)


def _timestamp(day: date, index: int) -> int:
    """Noon UTC + index minutes: GitHub buckets contributions by UTC date."""
    return calendar.timegm(day.timetuple()) + 12 * 3600 + index * 60


def _data(payload: str) -> bytes:
    raw = payload.encode("utf-8")
    return b"data %d\n%s\n" % (len(raw), raw)


def init_repo(workdir: Path, branch: str) -> None:
    if (workdir / "HEAD").exists():
        return
    workdir.parent.mkdir(parents=True, exist_ok=True)
    git("init", "--quiet", "--bare", "--initial-branch", branch, str(workdir))
    git("config", MARKER_KEY, "true", cwd=workdir)


def fetch_existing(workdir: Path, remote: str, branch: str) -> None:
    """Fetch the remote branch (the current drawing) as EXISTING_REF."""
    init_repo(workdir, branch)
    git("fetch", "--quiet", "--no-tags", remote, f"+refs/heads/{branch}:{EXISTING_REF}", cwd=workdir)


def existing_days(workdir: Path) -> dict[date, int]:
    """Commits per day (UTC author date) of the fetched drawing."""
    stamps = git("log", "--format=%at", EXISTING_REF, cwd=workdir).split()
    return dict(Counter(datetime.fromtimestamp(int(stamp), timezone.utc).date() for stamp in stamps))


def foreign_files(workdir: Path) -> set[str]:
    """Files touched by the fetched history other than the tool's own log file."""
    names = git("log", "--format=", "--name-only", EXISTING_REF, cwd=workdir).split("\n")
    return {name for name in names if name.strip()} - {LOG_FILE}


def build(
    workdir: Path,
    schedule: list[tuple[date, int]],
    name: str,
    email: str,
    message: str,
    branch: str,
    parent: str | None = None,
) -> int:
    """Create `count` commits on each scheduled day, on top of `parent` if given."""
    init_repo(workdir, branch)
    identity = f"{name} <{email}>".encode()
    process = subprocess.Popen(
        ["git", "fast-import", "--quiet", "--done"],
        cwd=workdir,
        stdin=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    total = 0
    assert process.stdin is not None
    for day, count in schedule:
        for index in range(count):
            total += 1
            stamp = b"%s %d +0000\n" % (identity, _timestamp(day, index))
            process.stdin.write(b"commit refs/heads/%s\n" % branch.encode())
            process.stdin.write(b"author " + stamp + b"committer " + stamp)
            process.stdin.write(_data(message))
            if parent and total == 1:
                process.stdin.write(b"from %s\n" % parent.encode())
            process.stdin.write(b"M 100644 inline %s\n" % LOG_FILE.encode())
            process.stdin.write(_data(f"{day.isoformat()} #{index + 1}"))
    process.stdin.write(b"done\n")
    _, stderr = process.communicate()
    if process.returncode:
        raise GitError(stderr.decode(errors="replace").strip() or "git fast-import failed")
    return total


def batch_ends(total: int, size: int) -> list[int]:
    """Index (0-based) of the last commit of each push batch."""
    ends = list(range(size - 1, total, size))
    if not ends or ends[-1] != total - 1:
        ends.append(total - 1)
    return ends if total else []


def push(
    workdir: Path,
    remote: str,
    branch: str,
    batch_size: int,
    delay: float,
    force: bool,
    progress: Callable[[int, int, int], None],
    sleep: Callable[[float], None] = time.sleep,
    base: str | None = None,
) -> int:
    """Push history oldest first, `batch_size` commits at a time. Returns the number of pushes.

    `base`: commits already on the remote (only the ones after it are pushed).
    """
    shas = git("rev-list", "--reverse", f"{base}..{branch}" if base else branch, cwd=workdir).split()
    ends = batch_ends(len(shas), batch_size)
    for number, end in enumerate(ends, 1):
        progress(number, len(ends), end + 1)
        plus = "+" if force and number == 1 else ""
        refspec = f"{plus}{shas[end]}:refs/heads/{branch}"
        for attempt in range(1, MAX_ATTEMPTS + 1):
            try:
                git("push", "--quiet", remote, refspec, cwd=workdir)
                break
            except GitError as error:
                if _FATAL.search(str(error)) or attempt == MAX_ATTEMPTS:
                    raise
                delay = min(max(delay, 1.0) * 2, MAX_DELAY)  # slow down for the rest of the run too
                sleep(delay)
        if number < len(ends):
            sleep(delay)
    return len(ends)
